# Generated by Django 4.2.2 on 2023-06-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('trade_code', models.CharField(max_length=50)),
                ('trade_name', models.CharField(max_length=50)),
                ('institution_code', models.CharField(max_length=50)),
                ('instution_name', models.CharField(max_length=50)),
                ('results', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
