# Generated by Django 4.2.2 on 2023-06-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='institution_code',
        ),
        migrations.RemoveField(
            model_name='students',
            name='instution_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='trade_code',
        ),
        migrations.RemoveField(
            model_name='students',
            name='trade_name',
        ),
        migrations.AddField(
            model_name='students',
            name='verified',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(upload_to='verified'),
        ),
        migrations.AlterField(
            model_name='students',
            name='tt_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
